
alias ls='ls --color=auto'
# alias ll='ls -alF'
alias ll='ls -alFh --group-directories-first'
alias la='ls -A'
alias l='ls -CF'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias vmore="vim -u ~/.vimrc.more -"
alias bashrc="source ~/.bashrc"

alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'

alias pdf='qpdfview --unique'

alias fzv='vim "$(fzf || echo -c :q)"'

alias stmux='st -e tmux'
alias stmake='sudo make -C ~/repos/st clean install'
